---
openapi: 3.0.1
info:
  title: Seltzer API
  version: v1
  description: 'Documentation for the Seltzer API'
paths:
  "/api/v1/users/{user_id}/contacts":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      tags: ['User Contacts']
      summary: list contacts
      responses:
        '200':
          description: successful
    post:
      tags: ['User Contacts']
      summary: create contact
      responses:
        '200':
          description: successful
  "/api/v1/users/{user_id}/contacts/{id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      tags: ['User Contacts']
      summary: show contact
      responses:
        '200':
          description: successful
    patch:
      tags: ['User Contacts']
      summary: update contact
      responses:
        '200':
          description: successful
    put:
      tags: ['User Contacts']
      summary: update contact
      responses:
        '200':
          description: successful
    delete:
      tags: ['User Contacts']
      summary: delete contact
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      tags: ['Users']
      summary: list users
      responses:
        '200':
          description: successful
    post:
      tags: ['Users']
      summary: create user
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      tags: ['Users']
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      tags: ['Users']
      summary: update user
      responses:
        '200':
          description: successful
    put:
      tags: ['Users']
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      tags: ['Users']
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: 'http://localhost:3000/api/v1'
  description: 'Local development API server'
